all_search_app65:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=globalapp65'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=globalapp65'

all_search_app66:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=globalapp66'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=globalapp66'

all_search_h5:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=mobileweb'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=mobileweb'

all_search_online:
    url1:
        'http://10.2.25.24:8180/qrwservice/search?&action=autocomplete&source=globalonline'
    url2:
        'http://10.2.25.25:8180/qrwservice/search?&action=autocomplete&source=globalonline'

all_search_offline:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?source=offline&action=autocomplete'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?source=offline&action=autocomplete'


gs_app65:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=gsapp65'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=gsapp65'

gs_app66:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=gsapp66'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=gsapp66'

gs_h5:
    url1:
        'http://10.2.25.24:8180/appautocomplete/search?&action=autocomplete&source=jsweb'
    url2:
        'http://10.2.25.25:8180/appautocomplete/search?&action=autocomplete&source=jsweb'



