

all_search_app:
    url1:
        'http://10.8.119.199:8180/appautocomplete/search?&action=autocomplete&source=globalapp65'
    url2:
        'http://10.8.119.200:8180/appautocomplete/search?&action=autocomplete&source=globalapp65'

all_search_h5:
    url1:
        'http://10.8.119.199:8180/appautocomplete/search?&action=autocomplete&source=mobileweb'
    url2:
        'http://10.8.119.200:8180/appautocomplete/search?&action=autocomplete&source=mobileweb'

all_search_online:
    url1:
        'http://10.8.119.199:8140/qrwservice/search?&action=autocomplete&source=globalonline'
    url2:
        'http://10.8.119.200:8140/qrwservice/search?&action=autocomplete&source=globalonline'

gs_app:
    url1:
        'http://10.8.119.199:8180/appautocomplete/search?&action=autocomplete&source=gsapp64'
    url2:
        'http://10.8.119.200:8180/appautocomplete/search?&action=autocomplete&source=gsapp64'

gs_online:
    url1:
        'http://10.8.119.199:8180/appautocomplete/search?&action=autocomplete&source=jsweb'
    url2:
        'http://10.8.119.200:8180/appautocomplete/search?&action=autocomplete&source=jsweb'



